### ISSUE TITLE
WIP - Endpoint request example included in generated RAML doc

### ISSUE THREAD

**Issue by davifantasia** [commercetools/rmf-codegen#178] opened 2020-07-28 09:48 UTC
## Example Programming Languages

From my discussion with @jenschude these two languages can be implemented first:  

* cURL
* Node.js

Other languages gets complicated quickly. Preference is to start with cURL.

#### Get

```
$curl -H "${tokenHeader}" "${baseUrl}/products"
#equals
$curl -H 'Authorization: Bearer kLhYhqi-XDOsWC_qpOHCkUx07WCYcIyU' https://api.{region}.{cloudProvider}.commercetools.com/demo-project-slug/products
```

For example details, see https://docs.commercetools.com/http-api-tutorial#all-products

#### Create

```
#!/bin/sh
curl -sH "Authorization: Bearer ACCESS_TOKEN" https://api.{region}.{cloudProvider}.commercetools.com/{projectKey}/types -d @- << EOF
{
  "key": "customer-preferredShoeSize",
  "name": { "en": "Additional field to store preferred shoe size" },
  "resourceTypeIds": ["customer"],
  "fieldDefinitions": [
    {
      "type":{
        "name":"LocalizedString"
      },
      "name":"preferredShoeSize",
      "label":{
        "en":"Preferred Shoe Size"
      },
      "required":false,
      "inputHint":"SingleLine"
    }
  ]
}
EOF
```

For example details, see https://docs.commercetools.com/tutorial-custom-types#creating-a-custom-type

#### Update

```
#!/bin/sh
curl -sH "Authorization: Bearer ACCESS_TOKEN" https://api.{region}.{cloudProvider}.commercetools.com/{projectKey}ustomers/{id-of-customer-jane-roe} -d @- << EOF
{
  "version":1,
  "actions":[
    {
      "action":"setCustomType",
      "type": {
        "key":"customer-preferredShoeSize"
      }
    }
  ]
}
EOF
```

For example details, see https://docs.commercetools.com/tutorial-custom-types#update-an-existing-customer-with-a-customfield

**Comment by davifantasia** [comment] 2020-07-28 09:51
@jenschude does this cover what you need?

**Comment by davifantasia** [comment] 2020-07-28 12:05
@nkThis is the issue I created.

**Comment by nkuehn** [comment] 2020-07-28 12:07
This is a duplicate of #169

**Comment by jenschude** [comment] 2020-07-29 08:04
True so. Somehow I didn't saw the other one. Will close this issue

**Closed by jenschude** 2020-07-29 08:04 UTC
